### ISSUE TITLE
[FEATURE] alongside working directory, include "ignored-directories" option

### ISSUE THREAD

**Issue by bnidevs** [creyD/prettier_action#100]
I would like prettier to run on every subdirectory of my repo EXCEPT one, and having to specify the majority of the repo is a pain.

Would prefer option to ignore 1 directory and run on the rest

**Comment by creyD** [comment]
@bnidevs this could be done via the .prettierignore, right? https://prettier.io/docs/en/ignore.html Wouldn't want to add features that are built into prettier. Feel free to reopen this, if this doesn't help you.

**Comment by bnidevs** [comment]
want to clarify: i have several react projects in one repo, alongside a build folder (that i did not add to the gitignore on purpose), so i think this would still be a helpful feature

**Comment by creyD** [comment]
What about the `file_pattern` option? You could exclude the files there within the GitHub action? This uses the gitignore syntax, so all files would technically be prettified, but only the relevant files would be pushed.
