### ISSUE TITLE
[FEATURE] Not Github Workflow Warnings

### ISSUE THREAD

**Issue by JuanDa237** [creyD/prettier_action#101]
**What would you like to change about the program?**
Fix the warning "Node.js 12 actions are deprecated." when the workflow is finished.

**Why do you think this is a cool idea?**
because it is always better to not have warnings

**Comment by JuanDa237** [comment]
This can be solved just with usign [Checkout V3](https://github.com/marketplace/actions/checkout) as is now suggested.
In the README.md is suggested to use v2

**Comment by creyD** [comment]
Thanks for the contribution, I merged this to dev for now.
