### ISSUE TITLE
Node.js 12 actions are deprecated.

### ISSUE THREAD

**Issue by Lakshan-Madushanka** [creyD/prettier_action#103]
It works fine but gives the below warning.
![Screenshot 2023-01-04 105607](https://user-images.githubusercontent.com/47297673/210490291-b2204fe4-27a6-4640-978b-b41419c0acff.png)

**Comment by creyD** [comment]
@Lakshan-Madushanka This is actually not the prettier_action but the checkout action. If you bump it to v3 as suggested in @AnimeAllstar s readme update you should be fine. Please reopen this, if this is not the case!
