### ISSUE TITLE
[BUG] Shouldn't delete node_modules

### ISSUE THREAD

**Issue by burner1024** [creyD/prettier_action#108]
**What exactly happened?**

1. Run npm install
2. Run action.

**What should've happened?**
`node_modules` not deleted, as they are used in the following steps.

**Where did you encounter the problem?**

- Version 4.2

**Comment by creyD** [comment]
This happens because someone might not have the node_modules in gitignore. Will add an option "clean_node" which defaults to False, but if you need it, you can use it from the next version onwards.

**Comment by burner1024** [comment]
I think `node_modules` normally should be in `.prettierignore`, and if they are not, there's probably a reason for that.
That's 2 layers of protection already, and I don't really see the need for the 3rd one.

**Comment by creyD** [comment]
I agree, just don't want to change functionality if someone uses it like that. Could you please check against prettier_action@dev to verify the new option is working?

**Comment by burner1024** [comment]
Uhm, the run [failed](https://github.com/BGforgeNet/VScode-BGforge-MLS/actions/runs/3995320409/jobs/6854056248), but I don't understand what's happening.

**Comment by jorgenbs** [comment]
Had issues with this as well, took a some time to debug why my workflow was failing.

> I agree, just don't want to change functionality if someone uses it like that.

Consider switching to semantic versioning for this package so its easier to introduce breaking changes like this.

**Comment by creyD** [comment]
@jorgenbs I thought what I was doing is semantic versioning. v4.3 introduces this change, see changelog, v4.2 was the previous version.

**Comment by creyD** [comment]
@burner1024 Do you consider this bug fixed?

**Comment by burner1024** [comment]
Yes, sure.
