### ISSUE TITLE
'Error' reporting

### ISSUE THREAD

**Issue by matt-paul** [creyD/prettier_action#17]
**What would you like to change about the program?**
The following are currently reported as 'errors'

[error] No parser could be inferred for file: frontend/Dockerfile
[error] No parser could be inferred for file: frontend/Makefile
[error] No parser could be inferred for file: frontend/yarn.lock

**Suggestion**
It is disconcerting that these flag up red and are reported as an error, when it is expected behaviour.  Wondering if this is neccesary.  

Great action, thanks anyway.

**Comment by matt-paul** [comment]
Apologies, i thought i had passed in correct prettier options 😐. Closing this.

**Comment by creyD** [comment]
No worries! Tell me if you need help again :)
