### ISSUE TITLE
GITHUB_TOKEN: parameter not set in entrypoint.sh

### ISSUE THREAD

**Issue by adriaanvanrossum** [creyD/prettier_action#2]
It's missing the `GITHUB_TOKEN` variable. According to the [GitHub Docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#about-the-github_token-secret) this is automatically set in a repository. But somehow I get this error:

```
index.js 43ms
file2.js 8ms
file3.js 5ms
/entrypoint.sh: 7: /entrypoint.sh: GITHUB_TOKEN: parameter not set
Commiting and pushing changes...
##[error]Docker run failed with exit code 2
```

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/72518878-851f8600-3856-11ea-8cb4-0ffbcd2cdbab.jpg"></kbd>

Am I missing something?

**Comment by creyD** [comment]
I believe this is somehow possibly a bug in GitHub Actions. Please try to provide the TOKEN manually by adding it to your workflow file like this:

```
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by creyD** [comment]
Okay, now I got it: The docs you sent are the parameters you can add in your `action.yml`. But for security reasons I can't access them from my repository, so you have to provide them via your file.

**Comment by creyD** [comment]
In 25777abf0866caa4f418b23f1398983a473cf77f I added a simple example config file!

**Comment by adriaanvanrossum** [comment]
You example works great! Thanks
