### ISSUE TITLE
Prettier action is not failing on ugly files.

### ISSUE THREAD

**Issue by singla-shivam** [creyD/prettier_action#20]
I have this action config
```yaml
name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Prettier check
        uses: creyD/prettier_action@v2.2
        with:
          dry: true
          prettier_options: --check **/*.ts

      - name: Use deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run tests
        run: deno test
```

I am running a check on typescript files.

Here is the `.prettierrc`
```json
{
  "semi": false,
  "trailingComma": "all",
  "singleQuote": true,
  "printWidth": 70,
  "arrowParens": "always",
  "bracketSpacing": true
}
```

**What exactly happened?**
The action passed without fail, only showing warnings.
This is the output
```
Installing prettier...
/entrypoint.sh: line 40: : Permission denied
/usr/local/bin/prettier -> /usr/local/lib/node_modules/prettier/bin-prettier.js
+ prettier@2.1.2
added 1 package from 1 contributor in 0.765s
Prettifing files...
Files:
Checking formatting...
[warn] specs/when.test.ts
[warn] specs/whereAll.test.ts
[warn] specs/whereAny.test.ts
[warn] specs/zipWith.test.ts
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
Problem running prettier with --check **/*.ts
Nothing to commit. Exiting.
```

**What should've happened?**
It should have failed the check and so the action.

Here is the link for the [run](https://github.com/Jozty/Fae/runs/1172696795?check_suite_focus=true)

**Comment by creyD** [comment]
I don't think that our prettier action supports `.prettierrc` files yet, this is probably why it doesn't fail on your run.

**Comment by singla-shivam** [comment]
The whole codebase is formatted according to this `.prettierrc`. So if the action is following the default settings, then it should fail every time.

**Comment by creyD** [comment]
Please try this setup with the latest 3.0 prerelease version! This seems like #12

**Comment by creyD** [comment]
Any update on this @singla-shivam ?

**Comment by creyD** [comment]
Feel free to reopen this if the problem still exists after trying with the latest version.
