### ISSUE TITLE
[BUG] Dry run reporting unpretty files when all files match styles

### ISSUE THREAD

**Issue by davwheat** [creyD/prettier_action#37]
**What exactly happened?**
When performing a dry run, Prettier reports that all files match the code style, but this action reports unpretty files.

See: https://github.com/flarumite/simple-spoilers/runs/1731327132#step:4:19

**How did it look?**
![image](https://user-images.githubusercontent.com/7406822/105105920-fa96e580-5aac-11eb-8d8c-6fcc58016112.png)

**Comment by creyD** [comment]
Pretty weird, sorry I wasn't able to investigate, will take a couple of days more. Do you have an idea what causes this?

**Comment by davwheat** [comment]
Honestly I have no clue.

Prettier outputs that it all matches, then the action reports a failure.

I ended up switching to my own action in the end.

**Comment by fsz-codeshop** [comment]
Hi guys! Maybe it is caused by this block on entry point?
```
  if $INPUT_DRY; then
    echo "Prettier found unpretty files!"
    exit 1
  else
```

**Comment by creyD** [comment]
@fsz-codeshop

**Comment by fsz-codeshop** [comment]
Hi @creyD, you are indeed right. It is not working with the dev branch. I am getting:
```
Error:  No parser and no file path given, couldn't infer a parser.
```
I have forked and worked on top of the main branch for that dry-run fix.
Nevertheless, I have also checked out the last commit on dev before merging my changes and I am still getting the same error (87e1553a825c17f83a666a2fa0f4320c8e39c984). When using fsz-codeshop/prettier_action@issue-37-dry-run-reporting-unpretty I get it working as expected:
```
Installing prettier...
/usr/local/bin/prettier -> /usr/local/lib/node_modules/prettier/bin-prettier.js
+ prettier@2.2.1
added 1 package from 1 contributor in 0.627s
Prettifying files...
Files:
Checking formatting...
[warn] .github/PULL_REQUEST_TEMPLATE.md
[warn] docs/CONTRIBUTING.md
[warn] index.js
[warn] README.md
[warn] test.js
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
Problem running prettier with --check --ignore-path ./.prettierignore --config ./prettier.config.js **/*.{js,ts,md}
Nothing to commit. Exiting.
```

Maybe it is something else of the other changes?

**Comment by fsz-codeshop** [comment]
Furthermore, checking the provided link (https://github.com/creyD/prettier_test/runs/2313102123) it seems that it worked as expected
```
No unpretty files! Finishing dry-run.
```
Did I miss something?

**Comment by creyD** [comment]
> Furthermore, checking the provided link (https://github.com/creyD/prettier_test/runs/2313102123) it seems that it worked as expected
> 
> ```
> No unpretty files! Finishing dry-run.
> ```
> 
> Did I miss something?

It states that it worked, but there was a unpretty file and it even showed it in the "Files:" statement.

**Comment by fsz-codeshop** [comment]
Ok. I think I got it. 
The logic only works when using --check configuration because of the prettier command status code

Anyway, I reopened the PR with the change of the logic to handle the cases using --write + dry-run and --check + dry-run.

I have forked the prettier_test and ran some tests and it seems it is working as expected now. If you can check it =)
