### ISSUE TITLE
[BUG] git checkout command fails to find branch

### ISSUE THREAD

**Issue by FredyC** [creyD/prettier_action#4]
**What exactly happened?**
Failed check: https://github.com/FredyC/actions-test/pull/1/checks
Workflow file: https://github.com/FredyC/actions-test/blob/master/.github/workflows/prettier.yaml

**What should've happened?**
Prettified code should have been committed & pushed.

**How did it look?**
![image](https://user-images.githubusercontent.com/1096340/74613490-3a23b780-510f-11ea-92e4-1e48e66a8ccd.png)

It's pretty much copy & paste of your example, but for some reason, it fails in this weird way.

**Comment by creyD** [comment]
Thanks for submitting your report!

Could you try it again with the action@master? I added a small change that could potentially resolve this issue.

**Comment by creyD** [comment]
More info here: https://github.com/FredyC/actions-test/pull/1

**Comment by dancinllama** [comment]
I was struggling with this yesterday as well.  Thanks for fixing!
