### ISSUE TITLE
[BUG] Failed push when using push to master as trigger

### ISSUE THREAD

**Issue by FredyC** [creyD/prettier_action#5]
**What exactly happened?**
Failed run: https://github.com/FredyC/actions-test/runs/450564625
Workflow: https://github.com/FredyC/actions-test/blob/master/.github/workflows/prettier.yml

**What should've happened?**
Prettified code should have been pushed

**How did it look?**
![image](https://user-images.githubusercontent.com/1096340/74657622-ed80c080-5190-11ea-8191-53fd731cbdec.png)

Me again. I've decided to trigger this action on a push to master as it just behaves oddly with PRs. For some reason the `INPUT_BRANCH` variable is empty.

**Comment by creyD** [comment]
You use the action on push, where there is no `head_ref` branch specified. If you want to run your action on push, then please specify the branch you are pushing to in the branch parameter!

I will add this to the readme tomorrow!

**Comment by FredyC** [comment]
I see. I am kinda failing to find docs on that. It does work if I hard code master as a branch input to the action. But what if the push was for more than a single branch? Is there some different parameter that can be used?
