### ISSUE TITLE
[DOCS] Improve documentation 

### ISSUE THREAD

**Issue by TomCockram** [creyD/prettier_action#50]
**What would you like to change about the program?**
I believe the documentation needs updating or improving as I tried to use the options below and always got the message that they were unknown options? 

Providing some examples of how you're meant to use these options would help. Also showing an action that uses more than one option at a time would show how to chain them in case you have to do something different. 

How are you meant to use the options like --dry and --only_changed? 

```
[warn] Ignored unknown option --dry=true.
[warn] Ignored unknown option --only_changed=true. 
```

```
[warn] Ignored unknown option --dry.
[warn] Ignored unknown option --only_changed.
```

Have tried both of these and always complained about unknown options. 

**Why do you think this is a cool idea?**
The documentation needs to be more clear on the examples and how you're meant to use them. Also, I believe there is something that is required but is not mentioned as required.

`Error:  No parser and no file path given, couldn't infer a parser.` 

I get this error but no idea how to fix or what I'm missing.

Happy to update the readme file if I have the correct information!

**Comment by creyD** [comment]
You may create a PR and I will merge if it is beneficial. Thanks!

**Comment by creyD** [comment]
Also both of these options will need to be used in your .yml file under the with: section of the configuration:

with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write **/*.{js,md}
        dry: True

The second example actually shows this for only-changed, which is why I am closing this. If you have other concerns, please reopen!
