### ISSUE TITLE
[BUG] Checkout: Error search process (Using a fork).

### ISSUE THREAD

**Issue by Danila-hub** [creyD/prettier_action#54]
**What exactly happened?**

1. Go to your fork, or create it from the main repository. 
2. In the fork, create a new branch whose name does not exist in the main repository.
**For example feature_534.** 
3. We finish work in our fork in the feature_534 branch, make a commit and make a pull request to the main repository - we get a prettier action error:
 /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/**feature_534***:refs/remotes/origin/**feature_534*** +refs/tags/**feature_534***:refs/tags/**feature_534***
The process '/usr/bin/git'  - failed with exit code 1

4. We don't get an error if we use the branch name in our fork, which is in the main repository.
for example:
_the main repository exists: feature_123.
In the fork we create feature_123 branch and do pull request in main repo - Prettier work done._
 
**What should've happened?**
The pretter action should work correctly, provided that the pull request is made from an external fork and a branch that does not exist in the main repository. 

**How did it look?**
![изображение](https://user-images.githubusercontent.com/55277394/119146292-27570b80-ba53-11eb-9a5c-30b9f9f105c2.png)

 - OS: [iOS, Win10, Linux]
- Repo: [https://github.com/imega-webrx/frontend]
 - Version [v.3.3]

**Comment by javila35** [comment]
Ran into this bug today. I'm going to attempt working on a solution, but I don't expect that I'll find it lol.

**Comment by Danila-hub** [comment]
> [Here's some more information about this bug.](https://github.com/stefanzweifel/git-auto-commit-action#using-the-action-in-forks-from-public-repositories)
> 
> After doing my own research, it's not possible to run this sort of action on a pull request from a forked repo. I'm currently testing running prettier after the pull request has been merged. I'll let you know.

Thanks a lot

**Comment by creyD** [comment]
@Danila-hub @javila35 The PR is still open, is there anything I can do to fix this?

**Comment by nikbora** [comment]
I have also run into this issue and wonder if anyone has a good workaround?

**Comment by creyD** [comment]
@Danila-hub @javila35 The PR is still open, is there anything we can do here?

**Comment by javila35** [comment]
No, I think this issue can be closed. See this comment: https://github.com/creyD/prettier_action/issues/54#issuecomment-858891671
