### ISSUE TITLE
Add support to override the token used to push the changes

### ISSUE THREAD

**Issue by hpedrorodrigues** [creyD/prettier_action#55]
First of all, thanks for this project. 🚀 

**Problem**
I'm using this action in a specific project for every Pull Request, but after it pushes the changes back to the PR, I expect this push to trigger another action. However, this seems to not work.

**Why**
This occurs because pushes using the default environment variable `GITHUB_TOKEN` don't trigger a new workflow, even when configured. So as pointed in this [discussion][2] a possible solution is to create a personal token.

**What I've tried**
Following this idea, I've created a personal token, but as this action has no option to override the token yet, I tried to override the default env var `GITHUB_TOKEN`.

```yaml
env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
```

However, as the [docs][1] says, if we attempt to override the value of one of the default environment variables, the assignment is ignored.

**What would you like to change about the program?**
I'd like to have an option to override the token used to push the changes.
It could be a new environment variable or a new parameter to the action.

**Why do you think this is a cool idea?**
With this change, we'll be able to trigger another workflow after the fixes have been pushed.

Idk if I'm missing something here, so please let me know.

If you think this feature makes sense, I can start working on the PR.

[1]: https://docs.github.com/en/actions/reference/environment-variables#naming-conventions-for-environment-variables
[2]: https://github.community/t/push-from-action-does-not-trigger-subsequent-action/16854

**Comment by creyD** [comment]
Will be available in the next version.
