### ISSUE TITLE
[BUG] Can't commit to a repo that uses git LFS

### ISSUE THREAD

**Issue by simon-walton** [creyD/prettier_action#58]
Using v3.1 on ubuntu-latest. The repo uses git LFS (though not for any files processed by prettier).
Fails to commit any changes with the error "This repository is configured for Git LFS but 'git-lfs' was not found on your path." It looks like git-lfs is not installed in the docker container, although it is on the outer GHA VM.

Probably the fix is just to add `git-lfs` to the apk install line.

**Comment by joshgrift** [comment]
Seems to be fixed in "upstream" [stefanzweifel/git-auto-commit-action](https://github.com/stefanzweifel/git-auto-commit-action) See [PR 21](https://github.com/stefanzweifel/git-auto-commit-action/pull/21/files)

**Comment by creyD** [comment]
Sounds good, still sadly don't really have the time to test the DEV branch and so I can't create a new version just yet.

**Comment by creyD** [comment]
@joshgrift Do you think this is somehow possible with the new dev version action?
