### ISSUE TITLE
Commit with github actions bot

### ISSUE THREAD

**Issue by Piet2001** [creyD/prettier_action#63]
Is there an option to commit from the github actions[bot] user.
So not every commit will be from my account?

I will use this settings to commit. But don't know how to set it in you action.
```
git config user.name 'github-actions[bot]'
git config user.email 'github-actions[bot]@users.noreply.github.com'
```

**Comment by creyD** [comment]
For me it is a cooperation from my account and GitHub Actions account. In line 20 the config for our script is placed: https://github.com/creyD/prettier_action/blob/dev/entrypoint.sh
