### ISSUE TITLE
4.0 fails to recognise options available

### ISSUE THREAD

**Issue by creyD** [creyD/prettier_action#66]
@creyD The [4.0](https://github.com/creyD/prettier_action/releases/tag/v4.0) pre-release version [fails](https://github.com/dita-ot/docs/runs/3778251458) to recognize the options available in the [latest versions of prettier/plugin-xml](https://github.com/prettier/plugin-xml/blob/main/CHANGELOG.md#110---2021-09-26):

    [warn] Ignored unknown option { xmlSelfClosingSpace: false }.
    [warn] Ignored unknown option { xmlWhitespaceSensitivity: "strict" }. 
           Did you mean htmlWhitespaceSensitivity?

Reverting to v3.3 allows checks to [pass](https://github.com/dita-ot/docs/runs/3778465869).

_Originally posted by @infotexture in https://github.com/creyD/prettier_action/issues/48#issuecomment-932823588_

**Comment by fbartho** [comment]
Have you already reported this upstream to prettier @creyD? I just ran across this myself when using prettier on the CLI

**Comment by creyD** [comment]
Good to hear!
