### ISSUE TITLE
[BUG] Prettier exits with code 1 in dry run when all files are already formatted.

### ISSUE THREAD

**Issue by rutajdash** [creyD/prettier_action#72]
**What exactly happened?**
Prettier exited with code 1 resulting in a failed step even when it found all files formatted correctly.

**What should've happened?**
Prettier should exit with code 0 (no error)

**How did it look?**

**Where did you encounter the problem?**
 - OS: ubuntu-latest
 - Action Version - v4.0

The repo is private and it was running on a fork but all permissions were given, even write permissions which wouldn't be required IMO.

**Screenshots**
Error:
![image](https://user-images.githubusercontent.com/33367546/143774569-b2930a44-d3f9-45b7-83d1-b85ea37d711f.png)

The configurations:
Action:
![image](https://user-images.githubusercontent.com/33367546/143774508-b5c028b5-5325-429c-821b-ac2a8a12c5c8.png)

Prettierrc:
![image](https://user-images.githubusercontent.com/33367546/143774546-8701576d-057c-4422-b5f1-896feea4da91.png)

**Comment by creyD** [comment]
@fsz-codeshop This seems like its happening inside the lines 94-97 in `entrypoint.sh`. Could you please take a look here?

**Comment by creyD** [comment]
Could you please try to reproduce and look if it still happens with v4.1.1? I tried a similar process and it worked alright with the current version @rutajdash

**Comment by fsz-codeshop** [comment]
@creyD sorry for the late reply. I was checking this issue and something if off.
According to the print screens "prettier options" is using --check, so the __git_changed()_ should not be entering block 92-132 and should run the block 133-142.

I suspect there is something on the workflow that is making the "git status -s" return true for his particular case.
@rutajdash is your workflow doing any other work on the local checked out code that might be making the "git status -s" be returning true?

**Comment by rutajdash** [comment]
> Could you please try to reproduce and look if it still happens with v4.1.1? I tried a similar process and it worked alright with the current version @rutajdash 

I'll definitely test this out and get back to you.

**Comment by rutajdash** [comment]
> @creyD sorry for the late reply. I was checking this issue and something if off.
> According to the print screens "prettier options" is using --check, so the __git_changed()_ should not be entering block 92-132 and should run the block 133-142.
> 
> I suspect there is something on the workflow that is making the "git status -s" return true for his particular case.
> @rutajdash is your workflow doing any other work on the local checked out code that might be making the "git status -s" be returning true?

I'm using a fresh workflow but I'm also using GitHub Artifacts, so that may be adding some files. It's possible.

**Comment by semseysandor** [comment]
I had the exact same issue. Running `git status -s` before `prettier` in the workflow revealed that a previous step (code style check with `php-cs-fixer`) created a cache file with unexpected (at least for me) name.
After changing that filename to what was already ignored in `.gitignore` , `git status -s` reported no change and `prettier` finished successfully.

So, I think this issue could be closed as "user error".

**Comment by creyD** [comment]
@rutajdash Could you please check out @semseysandor answer and reopen if needed? Thank you @semseysandor
