### ISSUE TITLE
[FEATURE] Import Sort

### ISSUE THREAD

**Issue by craig-dae** [creyD/prettier_action#8]
Please consider adding import sorting to this plugin: 

https://www.npmjs.com/package/prettier-plugin-import-sort

**Comment by creyD** [comment]
Sounds cool, considering that it is 0.0.4 I don't know if it wouldn't compromise reliability of the overall script?

**Comment by creyD** [comment]
Do you have any experience on how reliable the module is?

**Comment by creyD** [comment]
@craig-dae any updates?

**Comment by craig-dae** [comment]
Hey, sorry for not replying. 

You make a good point. I agree that creating a dependency on a plugin that is version 0.0.4 creates more problems than it solves. Thank you for responding.
