### ISSUE TITLE
[BUG] Running prettier in the absence of package.json and node_modules

### ISSUE THREAD

**Issue by Anselmoo** [creyD/prettier_action#83]
**What exactly happened?**

I want to use `creyD/prettier_action@v4.1` for checking if the `json` and `md` files are fine.

Locally it's working fine via `homebrew`

```shell
prettier --write **.md
```

But the action always returns the following error:

```terminal
No node_modules/ folder.
No package-lock.json file.
```

I try to exclude both via .prettierignore, but it is not working.

**Comment by creyD** [comment]
Please try this with the current version v4.1.1 and see if it works

**Comment by Anselmoo** [comment]
@creyD thx for your quick help, which actually helps a lot
