### ISSUE TITLE
[BUG]: Prettier refuses to commit

### ISSUE THREAD

**Issue by im-coder-lg** [creyD/prettier_action#89]
**What exactly happened?**
I executed Prettier with `workflow_dispatch` but it always failed while committing. It says that it can't commit since it's blocked.

1. Go to my new blog repo's actions page [here](https://github.com/im-coder-lg/docusaurus-blog/actions).
2. Click on the Prettier PR workflow(need to change this to Prettier, so click whatever has Prettier in it).
3. See all latest runs
4. See error in logs

**What should've happened?**
Prettier should've committed the changes flawlessly, like on the repo PRs.

**How did it look?**
This line:
https://github.com/im-coder-lg/docusaurus-blog/runs/4991433098?check_suite_focus=true#step:5:72

**Where did you encounter the problem?**

- Repo: [Above but I'll put here too](https://github.com/im-coder-lg/docusaurus-blog)
- Version 4.2

**Comment by creyD** [comment]
Hi, this sounds like an issue with the setup. Maybe this helps: https://github.community/t/refusing-to-allow-a-github-app-to-create-or-update-workflow-without-workflows-permission/182573/2

**Comment by im-coder-lg** [comment]
So, are you saying that I should make a PAT with workflow edit perms and add it to the workflow? I'll try that and report back.

**Comment by im-coder-lg** [comment]
Ah, it works now! Do you have a documentation site? I'll try adding a simple guide for this so that no one else gets confused.

**Comment by creyD** [comment]
Thanks, that sounds good. You may add this to the readme if that's ok?

**Comment by im-coder-lg** [comment]
I'll do it as soon as I am free :)
