### ISSUE TITLE
[FEATURE] Specify prettier version

### ISSUE THREAD

**Issue by akgoogle** [creyD/prettier_action#9]
**What would you like to change about the program?**
A way to specify the prettier version number.

**Why do you think this is a cool idea?**
Some node versions don't support prettier v2.x.x. I'd like to use this action with prettier v1.19.1

**Comment by creyD** [comment]
Good idea! I implemented a test version in a new branch, will test tomorrow!

**Comment by creyD** [comment]
I implemented it for now, you may test it and I would appreciate feedback!

**Comment by akgoogle** [comment]
Yeah, after upgrading to v2.2 of your action and specifying prettier_version, it works as intended. Thanks!
```
        uses: creyD/prettier_action@v2.2
        with:
          prettier_version: "1.19.1"
```

**Comment by creyD** [comment]
Great! :)
