### ISSUE TITLE
Ignore minified files

### ISSUE THREAD

**Issue by hatamiarash7** [creyD/prettier_action#93]
How can I ignore minified files? For example, I don't need to format `*.min.js` and `*.min.css` files.  
Can I add multiple patterns? like this:

```yml
prettier_options: --write " **/*.js, **/*.!(min.js) " # Obviously not work
```

Or

```yml
prettier_options: --write **/*{!(.min.)css,!(.min.)js} # Not work too
```

We can do this by a simple `.prettierignore` file but is there any way to ignore these files in command? I have no idea about that

**Comment by creyD** [comment]
[This is answered in this post](https://stackoverflow.com/a/66340727/7454177)
